version: "3"

services:
  nuxt:
    build: ./
    container_name: yammi
    restart: always
    ports:
      - "3001:3000"
    command:
      "npm run start"

#  nginx:
#    image: nginx:1.13
#    container_name: vuevixens-nginx
#    ports:
#      - "3000:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - nuxt
